aliases: []
creation_timestamp: 1757972042522
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1757972042522
metrics: null
model_id: m-4f8ae355b8dc4a919ca72a7804f1271c
name: Fraud_detection
params: null
run_id: ''
run_link: ''
source: file:///C:/Users/Jashuva/Desktop/fraud_detection_Mlops/mlruns/956049052120432499/models/m-4f8ae355b8dc4a919ca72a7804f1271c/artifacts
status: READY
status_message: null
storage_location: file:///C:/Users/Jashuva/Desktop/fraud_detection_Mlops/mlruns/956049052120432499/models/m-4f8ae355b8dc4a919ca72a7804f1271c/artifacts
user_id: null
version: 1
